# Redirects configuration
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers configuration
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

# Build settings
[build]
  command = "yarn build && yarn conditionally-build-storybook && yarn sitemap"
  publish = "out"

# Environment variables
[build.environment]
  NODE_VERSION = "14"
  YARN_VERSION = "1.19.0"

# Edge functions
[edge_handlers]
  handler = "/client/netlify/functions"

# Functions
[functions]
  directory = "/client/netlify/functions"
